version: '2.1'
services:
  eureka:
    build: ./eureka
    container_name: springcloud_eureka
    image: gitlab-registry.adorsys.de/springcloud/eureka:latest
    ports:
    - 8761:8761
  discovery:
    build: ./discoveryclient
    container_name: springcloud_discoveryclient
    image: gitlab-registry.adorsys.de/springcloud/discovery:latest
    ports:
    - 8080:8080
    links:
    - eureka
  ribbon:
    build: ./ribbon
    container_name: springcloud_ribbon
    image: gitlab-registry.adorsys.de/springcloud/ribbon:latest
    ports:
    - 8088:8088
    links:
    - eureka
    - helloworld_0
    - helloworld_1
    - helloworld_2
  helloworld_0:
    build: ./helloworld
    container_name: springcloud_helloworld_0
    image: gitlab-registry.adorsys.de/springcloud/helloworld:latest
    links:
    - eureka
    environment:
    - eureka_instance_hostname=helloworld_0
    - helloworld_text=abc0
  helloworld_1:
    build: ./helloworld
    container_name: springcloud_helloworld_1
    image: gitlab-registry.adorsys.de/springcloud/helloworld:latest
    links:
    - eureka
    environment:
    - eureka_instance_hostname=helloworld_1
    - helloworld_text=abc1
  helloworld_2:
    build: ./helloworld
    container_name: springcloud_helloworld_2
    image: gitlab-registry.adorsys.de/springcloud/helloworld:latest
    links:
    - eureka
    environment:
    - eureka_instance_hostname=helloworld_2
    - helloworld_text=abc2
