version: '2.1'
services:
  eureka:
    build: ./eureka
    container_name: springcloud_eureka
    image: local/springcloud/eureka:latest
    ports:
    - 8761:8761
  config:
    build: ./config
    container_name: springcloud_config
    image: local/springcloud/config:latest
    ports:
    - 8888:8888
  discovery:
    build: ./discoveryclient
    container_name: springcloud_discoveryclient
    image: local/springcloud/discovery:latest
    ports:
    - 8080:8080
    links:
    - eureka
  ribbon:
    build: ./ribbon
    container_name: springcloud_ribbon
    image: local/springcloud/ribbon:latest
    ports:
    - 8088:8088
    links:
    - eureka
    - helloworld_0
    - helloworld_1
    - helloworld_2
  helloworld_0:
    build: ./helloworld
    container_name: springcloud_helloworld_0
    image: local/springcloud/helloworld:latest
    links:
    - eureka
    - config
    environment:
    - eureka_instance_hostname=helloworld_0
    - spring_cloud_config_name=hello-world-0
    restart: always
  helloworld_1:
    build: ./helloworld
    container_name: springcloud_helloworld_1
    image: local/springcloud/helloworld:latest
    links:
    - eureka
    - config
    environment:
    - eureka_instance_hostname=helloworld_1
    - spring_cloud_config_name=hello-world-1
    restart: always
  helloworld_2:
    build: ./helloworld
    container_name: springcloud_helloworld_2
    image: local/springcloud/helloworld:latest
    links:
    - eureka
    - config
    environment:
    - eureka_instance_hostname=helloworld_2
    - spring_cloud_config_name=hello-world-2
    restart: always
