version: '2.1'
services:
  eureka:
    build: ./eureka
    container_name: springcloud_eureka
    image: local/springcloud/eureka:latest
    environment:
      - JAVA_OPTS=-Xmx128m
    ports:
    - 8761:8761
    networks:
      - spring_cloud_network
  config:
    build: ./config
    container_name: springcloud_config
    image: local/springcloud/config:latest
    environment:
      - JAVA_OPTS=-Xmx128m
    networks:
      - spring_cloud_network
  discovery:
    build: ./discoveryclient
    container_name: springcloud_discoveryclient
    image: local/springcloud/discovery:latest
    environment:
      - JAVA_OPTS=-Xmx128m
    networks:
      - spring_cloud_network
  ribbon:
    build: ./ribbon
    container_name: springcloud_ribbon
    image: local/springcloud/ribbon:latest
    environment:
      - JAVA_OPTS=-Xmx128m
    networks:
      - spring_cloud_network
  zuul:
    build: ./zuul
    container_name: springcloud_zuul
    image: local/springcloud/zuul:latest
    environment:
      - JAVA_OPTS=-Xmx128m
    ports:
      - 8081:8081
    networks:
      - spring_cloud_network
  helloworld-0:
    build: ./helloworld
    container_name: springcloud_helloworld_0
    image: local/springcloud/helloworld:latest
    environment:
      - JAVA_OPTS=-Xmx128m
      - eureka_instance_hostname=helloworld-0
      - spring_cloud_config_name=hello-world-0
    restart: always
    networks:
      - spring_cloud_network
  helloworld-1:
    build: ./helloworld
    container_name: springcloud_helloworld_1
    image: local/springcloud/helloworld:latest
    environment:
      - JAVA_OPTS=-Xmx128m
      - eureka_instance_hostname=helloworld-1
      - spring_cloud_config_name=hello-world-1
    restart: always
    networks:
      - spring_cloud_network
  helloworld-2:
    build: ./helloworld
    container_name: springcloud_helloworld_2
    image: local/springcloud/helloworld:latest
    environment:
      - JAVA_OPTS=-Xmx128m
      - eureka_instance_hostname=helloworld-2
      - spring_cloud_config_name=hello-world-2
    restart: always
    networks:
      - spring_cloud_network

networks:
  spring_cloud_network:
