spring:
  application:
    name: ribbon

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hello-world:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:8888, http://localhost:8889
    ServerListRefreshInterval: 15000
